;
; jaguar_regs.s -- AUTO-GENERATED.  DO NOT EDIT BY HAND.
;
; Single source of truth for Jaguar register addresses, MMIO offsets,
; blitter command bits, and IRQ enums used by the acid-test ROMs.
;
; Generated by test/acid/scripts/gen-jaguar-regs.py from:
;   src/tom/blitter.c    (blitter cmd bits + register offsets)
;   src/tom/tom.h        (TOM IRQ enum, TOM register offsets)
;   src/jerry/jerry.h    (JERRY IRQ2 enum)
;   src/jerry/dsp.h      (DSP base addresses)
;   src/tom/gpu.h        (GPU base addresses)
;
; If a base address or bit field changes in the C source, this file
; will pick it up next time `make` runs in test/acid/.  Tests should
; ALWAYS reference these symbols by name (BCOMPEN, IRQ2_TIMER1, etc.)
; rather than hard-coding hex literals.
;

;; ================================================================
;; Section 1: subsystem base addresses
;; ================================================================

TOM_BASE        equ     $00F00000
GPU_BASE        equ     $00F02100
GPU_RAM         equ     $00F03000
BLIT_BASE       equ     $00F02200
JERRY_BASE      equ     $00F10000
DSP_BASE        equ     $00F1A100
DSP_RAM         equ     $00F1B000

;; ================================================================
;; Section 2: TOM register offsets (TOM_BASE + ...)
;; ================================================================

TOM_MEMCON1     equ     $00F00000   ; TOM_BASE + $00
TOM_MEMCON2     equ     $00F00002   ; TOM_BASE + $02
TOM_HC          equ     $00F00004   ; TOM_BASE + $04
TOM_VC          equ     $00F00006   ; TOM_BASE + $06
TOM_OLP         equ     $00F00020   ; TOM_BASE + $20
TOM_OLP_LO      equ     $00F00020   ; TOM_BASE + $20
TOM_OLP_HI      equ     $00F00022   ; TOM_BASE + $22
TOM_VBB         equ     $00F0002A   ; TOM_BASE + $2A
TOM_VBE         equ     $00F0002C   ; TOM_BASE + $2C
TOM_VS          equ     $00F0002E   ; TOM_BASE + $2E
TOM_VDB         equ     $00F00030   ; TOM_BASE + $30
TOM_VDE         equ     $00F00032   ; TOM_BASE + $32
TOM_VEB         equ     $00F00034   ; TOM_BASE + $34
TOM_VEE         equ     $00F00036   ; TOM_BASE + $36
TOM_VI          equ     $00F0004E   ; TOM_BASE + $4E
TOM_PIT0        equ     $00F00050   ; TOM_BASE + $50
TOM_PIT1        equ     $00F00052   ; TOM_BASE + $52
TOM_BG          equ     $00F00058   ; TOM_BASE + $58
TOM_INT1        equ     $00F000E0   ; TOM_BASE + $E0
TOM_INT2        equ     $00F000E2   ; TOM_BASE + $E2

;; ================================================================
;; Section 3: blitter MMIO addresses (BLIT_BASE + ...)
;; ================================================================

B_A1_BASE       equ     $00F02200   ; BLIT_BASE + $00
B_A1_FLAGS      equ     $00F02204   ; BLIT_BASE + $04
B_A1_CLIP       equ     $00F02208   ; BLIT_BASE + $08
B_A1_PIXEL      equ     $00F0220C   ; BLIT_BASE + $0C
B_A1_STEP       equ     $00F02210   ; BLIT_BASE + $10
B_A1_FSTEP      equ     $00F02214   ; BLIT_BASE + $14
B_A1_FPIXEL     equ     $00F02218   ; BLIT_BASE + $18
B_A1_INC        equ     $00F0221C   ; BLIT_BASE + $1C
B_A1_FINC       equ     $00F02220   ; BLIT_BASE + $20
B_A2_BASE       equ     $00F02224   ; BLIT_BASE + $24
B_A2_FLAGS      equ     $00F02228   ; BLIT_BASE + $28
B_A2_MASK       equ     $00F0222C   ; BLIT_BASE + $2C
B_A2_PIXEL      equ     $00F02230   ; BLIT_BASE + $30
B_A2_STEP       equ     $00F02234   ; BLIT_BASE + $34
B_COMMAND       equ     $00F02238   ; BLIT_BASE + $38
B_PIXLINECOUNTER equ     $00F0223C   ; BLIT_BASE + $3C
B_SRCDATA       equ     $00F02240   ; BLIT_BASE + $40
B_DSTDATA       equ     $00F02248   ; BLIT_BASE + $48
B_DSTZ          equ     $00F02250   ; BLIT_BASE + $50
B_SRCZINT       equ     $00F02258   ; BLIT_BASE + $58
B_SRCZFRAC      equ     $00F02260   ; BLIT_BASE + $60
B_PATTERNDATA   equ     $00F02268   ; BLIT_BASE + $68
B_INTENSITYINC  equ     $00F02270   ; BLIT_BASE + $70
B_ZINC          equ     $00F02274   ; BLIT_BASE + $74
B_COLLISIONCTRL equ     $00F02278   ; BLIT_BASE + $78

;; ================================================================
;; Section 4: blitter COMMAND bits (write to B_COMMAND)
;; ================================================================

SRCEN           equ     $0001
SRCENZ          equ     $0002
SRCENX          equ     $0004
DSTEN           equ     $0008
DSTENZ          equ     $0010
DSTWRZ          equ     $0020
CLIPA1          equ     $0040
UPDA1F          equ     $0100
UPDA1           equ     $0200
UPDA2           equ     $0400
DSTA2           equ     $0800
GOURD           equ     $1000
GOURZ           equ     $2000
TOPBEN          equ     $4000
TOPNEN          equ     $8000
PATDSEL         equ     $00010000
ADDDSEL         equ     $00020000
Z_OP_INF        equ     $00040000
Z_OP_EQU        equ     $00080000
Z_OP_SUP        equ     $00100000
LFU_NAN         equ     $00200000
LFU_NA          equ     $00400000
LFU_AN          equ     $00800000
LFU_A           equ     $01000000
CMPDST          equ     $02000000
BCOMPEN         equ     $04000000
DCOMPEN         equ     $08000000
BKGWREN         equ     $10000000
SRCSHADE        equ     $40000000

BLIT_CMD_VALID_BITS equ     $5FFFFF7F   ; OR of every defined cmd field (lint mask)

;; LFU function lives in bits 21..24 (4-bit field).
;; Pre-shifted constants for each function.  Named
;; LFU_FN_X (not LFU_X) to avoid colliding with the
;; LFU_A / LFU_NA / LFU_AN / LFU_NAN cmd bits above.
LFU_FN_0        equ     $0000   ; LFU function = 0x0
LFU_FN_1        equ     $00200000   ; LFU function = 0x1
LFU_FN_2        equ     $00400000   ; LFU function = 0x2
LFU_FN_3        equ     $00600000   ; LFU function = 0x3
LFU_FN_4        equ     $00800000   ; LFU function = 0x4
LFU_FN_5        equ     $00A00000   ; LFU function = 0x5
LFU_FN_6        equ     $00C00000   ; LFU function = 0x6
LFU_FN_7        equ     $00E00000   ; LFU function = 0x7
LFU_FN_8        equ     $01000000   ; LFU function = 0x8
LFU_FN_9        equ     $01200000   ; LFU function = 0x9
LFU_FN_A        equ     $01400000   ; LFU function = 0xa
LFU_FN_B        equ     $01600000   ; LFU function = 0xb
LFU_FN_C        equ     $01800000   ; LFU function = 0xc
LFU_FN_D        equ     $01A00000   ; LFU function = 0xd
LFU_FN_E        equ     $01C00000   ; LFU function = 0xe
LFU_FN_F        equ     $01E00000   ; LFU function = 0xf

;; ================================================================
;; Section 5: TOM IRQ enum + bit-mask (INT1 low byte)
;; ================================================================

IRQ_VIDEO       equ     $0000   ; bit position in TOM_INT1 low byte
IRQ_VIDEO_MASK  equ     $0001
IRQ_GPU         equ     $0001   ; bit position in TOM_INT1 low byte
IRQ_GPU_MASK    equ     $0002
IRQ_OPFLAG      equ     $0002   ; bit position in TOM_INT1 low byte
IRQ_OPFLAG_MASK equ     $0004
IRQ_TIMER       equ     $0003   ; bit position in TOM_INT1 low byte
IRQ_TIMER_MASK  equ     $0008
IRQ_DSP         equ     $0004   ; bit position in TOM_INT1 low byte
IRQ_DSP_MASK    equ     $0010

;; ================================================================
;; Section 6: JERRY IRQ2 enum bits (JINTCTRL)
;; ================================================================

IRQ2_EXTERNAL   equ     $0001
IRQ2_DSP        equ     $0002
IRQ2_TIMER1     equ     $0004
IRQ2_TIMER2     equ     $0008
IRQ2_ASI        equ     $0010
IRQ2_SSI        equ     $0020

