//
// m68kinterface.c: Code interface to the UAE 68000 core and support code
//
// by James Hammons
// (C) 2011 Underground Software
//
// JLH = James Hammons <jlhamm@acm.org>
//
// Who  When        What
// ---  ----------  -------------------------------------------------------------
// JLH  10/28/2011  Created this file ;-)
//

#include <string.h>
#include "m68kinterface.h"
#include "cpudefs.h"
#include "inlines.h"
#include "cpuextra.h"
#include "readcpu.h"
#include "../core/state.h"
#include "../core/vjag_memory.h"
#include "../core/vjtrace.h"

// Exception Vectors handled by emulation
#define EXCEPTION_BUS_ERROR                2 /* This one is not emulated! */
#define EXCEPTION_ADDRESS_ERROR            3 /* This one is partially emulated (doesn't stack a proper frame yet) */
#define EXCEPTION_ILLEGAL_INSTRUCTION      4
#define EXCEPTION_ZERO_DIVIDE              5
#define EXCEPTION_CHK                      6
#define EXCEPTION_TRAPV                    7
#define EXCEPTION_PRIVILEGE_VIOLATION      8
#define EXCEPTION_TRACE                    9
#define EXCEPTION_1010                    10
#define EXCEPTION_1111                    11
#define EXCEPTION_FORMAT_ERROR            14
#define EXCEPTION_UNINITIALIZED_INTERRUPT 15
#define EXCEPTION_SPURIOUS_INTERRUPT      24
#define EXCEPTION_INTERRUPT_AUTOVECTOR    24
#define EXCEPTION_TRAP_BASE               32

// These are found in obj/cpustbl.c (generated by gencpu)

//extern const struct cputbl op_smalltbl_0_ff[];	/* 68040 */
//extern const struct cputbl op_smalltbl_1_ff[];	/* 68020 + 68881 */
//extern const struct cputbl op_smalltbl_2_ff[];	/* 68020 */
//extern const struct cputbl op_smalltbl_3_ff[];	/* 68010 */
extern const struct cputbl op_smalltbl_4_ff[];	/* 68000 */
extern const struct cputbl op_smalltbl_5_ff[];	/* 68000 slow but compatible.  */

// Externs, supplied by the user...
//extern int irq_ack_handler(int);

// TOM drives the 68K's only interrupt input (all Jaguar IRQs arrive as a
// level-2 request through TOM).  Declared here rather than via tom.h to
// keep the UAE core free of TOM's header dependencies.
extern int TOMIRQRequestActive(void);

// Function prototypes...
static INLINE void m68ki_check_interrupts(void);
void m68ki_exception_interrupt(uint32_t intLevel);
static INLINE uint32_t m68ki_init_exception(void);
static INLINE void m68ki_stack_frame_3word(uint32_t pc, uint32_t sr);
unsigned long IllegalOpcode(uint32_t opcode);
void BuildCPUFunctionTable(void);
void m68k_set_irq2(unsigned int intLevel);

// Local "Global" vars
static int32_t initialCycles;
cpuop_func * cpuFunctionTable[65536];

// Monotonic count of serviced interrupts/exceptions-by-IRQ. Diagnostic only:
// lets test harnesses distinguish "halted, will be woken" from "halted with a
// dead wake path" (lost wakeup). Exported via the m68k_* test-ABI wildcard.
static uint32_t m68kInterruptsServiced = 0;

unsigned int m68k_is_stopped(void)
{
	return regs.stopped ? 1 : 0;
}

unsigned int m68k_diag_interrupt_count(void)
{
	return m68kInterruptsServiced;
}

// By virtue of the fact that m68k_set_irq() can be called asychronously by
// another thread, we need something along the lines of this:
static int checkForIRQToHandle = 0;
static int IRQLevelToHandle = 0;

void M68KDebugHalt(void)
{
	regs.spcflags |= SPCFLAG_DEBUGGER;
}


void M68KDebugResume(void)
{
	regs.spcflags &= ~SPCFLAG_DEBUGGER;
}


/* ------------------------------------------------------------------------
 * 68000 prefetch queue, as far as self-modifying code can observe it
 * (issue #811).
 *
 * The 68000 holds two instruction words ahead of the decoder (IR/IRC).  At
 * an instruction boundary they are the words at PC and PC+2.  A write that
 * lands on a word the queue already holds does not change what executes;
 * the CPU runs the stale copy, and only a later refetch sees the new value.
 * Xenowings relies on that: at $350C, `ori.l #$04000400,(a1)` turns the next
 * two `addq.l #1,d6` into `addq.l #3,d6`, and its anti-tamper check only
 * passes if the old instructions run.
 *
 * This core reads every instruction word straight from memory.  Rather than
 * model the queue on every fetch, the main-RAM write paths do one compare
 * against a window around regs.pc (M68K_PF_NEAR) and call
 * M68KPrefetchSnoop() on a hit.  The snoop records the word as it was
 * before the write.  At the next dispatch, the recorded words that the
 * queue really held are kept (pf_resolve), swapped back into RAM for
 * exactly one instruction, then restored (M68KPrefetchDispatch).
 *
 * Which words the queue holds when the write lands depends on the order of
 * the instruction's bus cycles.  Two cases cover the instructions that
 * write memory:
 *
 *   - The final prefetch comes BEFORE the write: next_pc and next_pc+2 are
 *     both held.  This covers the read-modify-write ALU forms (ORI/ANDI/
 *     EORI/ADDI/SUBI #imm,<ea>; ADD/SUB/AND/OR/EOR Dn,<ea>; ADDQ/SUBQ;
 *     CLR/NEG/NEGX/NOT; Scc; shifts and bit ops on memory), MOVE to -(An),
 *     PEA (An), and ADDX/SUBX/ABCD/SBCD -(An).
 *   - The write comes BEFORE the final prefetch: only next_pc is held.
 *     This covers MOVE to (An), (An)+, (d16,An), (d8,An,Xn), (xxx).W and
 *     (xxx).L, MOVEM to memory, MOVEP to memory, LINK, and the other PEA
 *     modes.
 *
 * Sources: the bus-cycle sequences in Clock Signal's microcode-derived
 * 68000 (TomHarte/CLK, Processors/68000/Implementation/
 * 68000Implementation.hpp): Perform_np = "PerformDynamic(); Prefetch();"
 * then StoreOperand; MOVE_bw (An) = "Access(...); // nw" then
 * "Prefetch(); // np"; MOVE -(An) = np then nw; MOVEMtoM_finish ends with
 * the np; LINKw = np, push, np; MOVEPtoM = np, four writes, np.
 *
 * The generated _5 handlers do not encode this order: op_2080_5
 * (move.l Dn,(An)) refills before its write, which is not what the
 * hardware does.  So the class is decided here from OpcodeFamily and the
 * opcode, never from where the handler calls fill_prefetch.
 *
 * Known approximation: MOVE from a memory source to (xxx).L writes before
 * fetching next_pc at all on hardware; it is treated as "next_pc held".
 * ---------------------------------------------------------------------- */

#define PF_FREE    0
#define PF_FRESH   1	/* written by the instruction that just ran */
#define PF_QUEUED  2	/* the queue holds this word for the next dispatch */
#define PF_SWAPPED 3	/* stale word is in RAM while one instruction runs */
#define PF_SLOTS   24	/* 16 words of snoop window + 2 queued, rounded up */

typedef struct
{
	uint32_t addr;
	uint16_t oldv;		/* the word as the queue holds it */
	uint16_t newv;		/* RAM contents while swapped out */
	uint8_t  state;
	uint8_t  two;		/* FRESH: final prefetch came before the write */
	uint8_t  dirty;		/* SWAPPED: the running instruction wrote it */
} pf_entry;

static pf_entry pfEntry[PF_SLOTS];
static unsigned pfCount = 0;	/* slots in use (dense; [0, pfCount)) */

extern uint32_t pcQueue[0x400];
extern uint32_t pcQPtr;

/* 1 when the final prefetch of the running instruction precedes its writes,
 * so the queue holds next_pc and next_pc+2; 0 when only next_pc is held.
 * See the table above. */
static int pf_class_two(void)
{
	uint32_t ipc = pcQueue[(pcQPtr - 1) & 0x3FF];
	uint16_t op;

	if (OpcodeFamily != i_MOVE && OpcodeFamily != i_PEA
	    && OpcodeFamily != i_MVMLE && OpcodeFamily != i_MVPRM
	    && OpcodeFamily != i_LINK)
		return 1;
	if (OpcodeFamily == i_MVMLE || OpcodeFamily == i_MVPRM
	    || OpcodeFamily == i_LINK)
		return 0;
	if (ipc > 0x1FFFFE)
		return 1;	/* unreachable: the snoop only fires near RAM code */
	op = (uint16_t)GET16(jaguarMainRAM, ipc);
	if (OpcodeFamily == i_MOVE)
		return ((op >> 6) & 7) == 4;	/* destination -(An) */
	return ((op >> 3) & 7) == 2;		/* PEA (An) */
}

static void pf_remove(unsigned i)
{
	pfEntry[i] = pfEntry[--pfCount];
	pfEntry[pfCount].state = PF_FREE;
}

static void pf_sync_flag(void)
{
	if (pfCount)
		regs.spcflags |= SPCFLAG_PREFETCH;
	else
		regs.spcflags &= ~SPCFLAG_PREFETCH;
}

/* Called from the main-RAM branch of m68k_write_memory_8/16/32 before the
 * write lands, when M68K_PF_NEAR() hit.  Records each written word inside
 * [regs.pc - 16, regs.pc + 16).  The window has to reach behind regs.pc
 * because the generated handlers advance regs.pc before some writes and
 * after others. */
void M68KPrefetchSnoop(unsigned int address, unsigned int len)
{
	uint32_t w, end = address + len;
	unsigned i;
	int two = -1;

	for (w = address & ~1u; w < end; w += 2)
	{
		if ((uint32_t)(w + 16u - regs.pc) >= 32u || w > 0x1FFFFE)
			continue;
		for (i = 0; i < pfCount; i++)
			if (pfEntry[i].addr == w)
				break;
		if (i < pfCount)
		{
			/* Keep the first capture: the queue copy predates every
			 * write in this instruction. */
			if (pfEntry[i].state == PF_SWAPPED)
				pfEntry[i].dirty = 1;
			else
			{
				if (two < 0)
					two = pf_class_two();
				pfEntry[i].state = PF_FRESH;
				pfEntry[i].two   = (uint8_t)two;
			}
			continue;
		}
		if (pfCount >= PF_SLOTS)
			continue;
		if (two < 0)
			two = pf_class_two();
		pfEntry[pfCount].addr  = w;
		pfEntry[pfCount].oldv  = (uint16_t)GET16(jaguarMainRAM, w);
		pfEntry[pfCount].newv  = 0;
		pfEntry[pfCount].state = PF_FRESH;
		pfEntry[pfCount].two   = (uint8_t)two;
		pfEntry[pfCount].dirty = 0;
		pfCount++;
	}
	pf_sync_flag();
}

/* The queue is refilled from a new PC (exception, interrupt, reset, PC set
 * from outside the CPU): every recorded word is dropped.  A word swapped
 * out for the running instruction gets its real contents back first. */
void M68KPrefetchFlush(void)
{
	unsigned i;

	for (i = 0; i < pfCount; i++)
	{
		if (pfEntry[i].state == PF_SWAPPED && !pfEntry[i].dirty)
			SET16(jaguarMainRAM, pfEntry[i].addr, pfEntry[i].newv);
		pfEntry[i].state = PF_FREE;
	}
	pfCount = 0;
	regs.spcflags &= ~SPCFLAG_PREFETCH;
}

/* Would this entry still be in the queue when the CPU dispatches at pc? */
static int pf_keep(const pf_entry *e, uint32_t pc)
{
	if (e->addr == pc)
		return 1;
	if (e->addr != pc + 2)
		return 0;
	return e->state == PF_QUEUED || e->two;
}

/* Keep only the words the queue holds at dispatch PC `pc`.  Idempotent,
 * so a savestate can apply it without disturbing the run. */
static void pf_resolve(uint32_t pc)
{
	unsigned i = 0;

	while (i < pfCount)
	{
		if (pf_keep(&pfEntry[i], pc))
		{
			pfEntry[i].state = PF_QUEUED;
			i++;
		}
		else
			pf_remove(i);
	}
	pf_sync_flag();
}

/* Slow-path dispatch, taken only while SPCFLAG_PREFETCH is set.  Runs one
 * instruction with the queued words in RAM, then puts the real words back.
 * Swapping through RAM (instead of overriding the fetch) covers a stale
 * extension word as well as a stale opcode with no change to the fetch
 * path.  The swap is raw and lasts one instruction.  Anything else that
 * reads those two words during it sees the stale value: this instruction
 * reading its own code as data, or a GPU/DSP catch-up (M68KGPURAMSync) or
 * blit that this instruction's own register write starts.  That needs code
 * that patches the instruction stream and then has another processor read
 * the patched words within one 68K instruction; it is accepted as a known
 * approximation. */
#if defined(__GNUC__) || defined(__clang__)
#define PF_COLD __attribute__((noinline, cold))
#elif defined(_MSC_VER) && _MSC_VER >= 1400	/* VS2005+; msvc2003 lacks it */
#define PF_COLD __declspec(noinline)
#else
#define PF_COLD
#endif

/* Kept out of line (PF_COLD) so m68k_execute's hot loop stays as small as
 * it was: inlined, this path quadrupled the function. */
static PF_COLD int32_t M68KPrefetchDispatch(void)
{
	uint32_t pc = regs.pc, opcode;
	int32_t cycles;
	unsigned i;
	int cls;

	pf_resolve(pc);
	for (i = 0; i < pfCount; i++)
	{
		pfEntry[i].newv  = (uint16_t)GET16(jaguarMainRAM, pfEntry[i].addr);
		pfEntry[i].dirty = 0;
		pfEntry[i].state = PF_SWAPPED;
		SET16(jaguarMainRAM, pfEntry[i].addr, pfEntry[i].oldv);
	}

	opcode = get_iword(0);
	cycles = (int32_t)(*cpuFunctionTable[opcode])(opcode);
	/* Classified before anything is restored: it reads the opcode that ran. */
	cls = pf_class_two();

	/* Entries an exception flushed mid-instruction are already gone. */
	i = 0;
	while (i < pfCount)
	{
		pf_entry *e = &pfEntry[i];

		if (e->state != PF_SWAPPED)
		{
			i++;		/* FRESH: recorded by this instruction */
			continue;
		}
		if (e->dirty)
		{
			/* This instruction wrote the word: RAM keeps its value, and
			 * the queue copy (oldv) is resolved like any other write. */
			e->state = PF_FRESH;
			e->two   = (uint8_t)cls;
			i++;
			continue;
		}
		SET16(jaguarMainRAM, e->addr, e->newv);
		/* The IRC word becomes the next opcode only when the instruction
		 * was one word long and did not branch. */
		if (e->addr == pc + 2 && regs.pc == pc + 2)
		{
			e->state = PF_QUEUED;
			i++;
		}
		else
			pf_remove(i);
	}
	pf_sync_flag();
	return cycles;
}

/* Savestate packing, in fields that were always serialized and never used
 * (regs.prefetch_pc / regs.prefetch), so no STATE_VERSION change: old
 * states carry zeros and load as "nothing queued".
 *   prefetch_pc: bits 0-23 dispatch PC, bit 30 = word at PC queued,
 *                bit 31 = word at PC+2 queued
 *   prefetch:    queued word at PC in the high half, PC+2 in the low half
 * Packing does not modify the live entries (run-ahead determinism). */
#define PF_PACK_W0 0x40000000u
#define PF_PACK_W1 0x80000000u

static void pf_pack(void)
{
	uint32_t pc = regs.pc & 0x00FFFFFF, pp = 0, data = 0;
	unsigned i;

	for (i = 0; i < pfCount; i++)
	{
		if (!pf_keep(&pfEntry[i], regs.pc))
			continue;
		if (pfEntry[i].addr == regs.pc)
		{
			pp   |= PF_PACK_W0;
			data |= (uint32_t)pfEntry[i].oldv << 16;
		}
		else
		{
			pp   |= PF_PACK_W1;
			data |= pfEntry[i].oldv;
		}
	}
	regs.prefetch_pc = pp ? (pp | pc) : 0;
	regs.prefetch    = data;
}

static void pf_unpack(void)
{
	uint32_t pc = regs.prefetch_pc & 0x00FFFFFF;

	pfCount = 0;
	memset(pfEntry, 0, sizeof(pfEntry));
	if (regs.prefetch_pc & PF_PACK_W0)
	{
		pfEntry[pfCount].addr  = pc;
		pfEntry[pfCount].oldv  = (uint16_t)(regs.prefetch >> 16);
		pfEntry[pfCount].state = PF_QUEUED;
		pfCount++;
	}
	if (regs.prefetch_pc & PF_PACK_W1)
	{
		pfEntry[pfCount].addr  = pc + 2;
		pfEntry[pfCount].oldv  = (uint16_t)(regs.prefetch & 0xFFFF);
		pfEntry[pfCount].state = PF_QUEUED;
		pfCount++;
	}
	pf_sync_flag();
}


/* File-scope so m68k_done() below can reset it after freeing table68k. */
static uint32_t emulation_initialized = 0;

/* Symmetric counterpart to the lazy init in m68k_pulse_reset().
 * Defers the actual free to readcpu.c::free_table68k() so the table
 * is owned end-to-end by the module that allocates it (table68k is
 * declared in readcpu.h).  Called from JaguarDone() so ASAN sees a
 * clean shutdown. */
void m68k_done(void)
{
	free_table68k();
	emulation_initialized = 0;
}

// Pulse the RESET line on the CPU
void m68k_pulse_reset(void)
{
	// The first call to this function initializes the opcode handler jump table
	if (!emulation_initialized)
	{
		// Build opcode handler table here...
		read_table68k();
		do_merges();
		BuildCPUFunctionTable();
		emulation_initialized = 1;
	}

	regs.spcflags = 0;
	regs.stopped = 0;
	regs.remainingCycles = 0;
	m68kInterruptsServiced = 0;
	
	regs.intmask = 0x07;
	regs.s = 1;								// Supervisor mode ON

	// Read initial SP and PC
	m68k_areg(regs, 7) = m68k_read_memory_32(0);
	m68k_setpc(m68k_read_memory_32(4));
	refill_prefetch(m68k_getpc(), 0);
	M68KPrefetchFlush();
}


int m68k_execute(int num_cycles)
{
	if (regs.stopped)
	{
		regs.remainingCycles = 0;	// int32_t
		regs.interruptCycles = 0;	// uint32_t

		return num_cycles;
	}

	regs.remainingCycles = num_cycles;
	/*int32_t*/ initialCycles = num_cycles;

	regs.remainingCycles -= regs.interruptCycles;
	regs.interruptCycles = 0;

	/* Main loop.  Keep going until we run out of clock cycles */
	do
	{
		uint32_t opcode;
		int32_t cycles;

		// This is so our debugging code can break in on a dime.
		// Otherwise, this is just extra slow down :-P
		if (regs.spcflags & SPCFLAG_DEBUGGER)
		{
			// Not sure this is correct... :-P
			num_cycles = initialCycles - regs.remainingCycles;
			regs.remainingCycles = 0;	// int32_t
			regs.interruptCycles = 0;	// uint32_t

			return num_cycles;
		}
		if (checkForIRQToHandle)
		{
			checkForIRQToHandle = 0;
			m68k_set_irq2(IRQLevelToHandle);
		}
		else if (regs.intLevel > regs.intmask && TOMIRQRequestActive())
		{
			// The 68000 samples IPL0-2 at every instruction boundary, and
			// on the Jaguar every interrupt reaches the 68K as a level-2
			// request that TOM holds until the CPU's acknowledge cycle
			// (irq_ack_handler drops it).  So a request raised while SR's
			// mask is already >= 2 is not lost: it is taken as soon as an
			// RTE lowers the mask.
			//
			// Sampling only at the instant of assertion (the branch above)
			// dropped such requests permanently.  Tempest 2000 enables
			// video + TOM PIT (INT1 = $09); the PIT beats against the frame
			// rate and fires inside the PIT handler once every 161 frames,
			// swallowing that frame's vertical interrupt -- the game then
			// skips its object-list refresh and the OP replays an exhausted
			// bitmap object, collapsing the playfield into a band at the top
			// of the screen for exactly one frame (#187).
			m68ki_exception_interrupt(regs.intLevel);
		}

#ifdef M68K_HOOK_FUNCTION
		M68KInstructionHook();
#endif
		if (regs.spcflags & SPCFLAG_PREFETCH)
			cycles = M68KPrefetchDispatch();	/* see the queue model above */
		else
		{
			opcode = get_iword(0);
			cycles = (int32_t)(*cpuFunctionTable[opcode])(opcode);
		}
		regs.remainingCycles -= cycles;
	}
	while (regs.remainingCycles > 0);

	regs.remainingCycles -= regs.interruptCycles;
	regs.interruptCycles = 0;

	// Return # of clock cycles used
	return initialCycles - regs.remainingCycles;
}


void m68k_set_irq(unsigned int intLevel)
{
	// We need to check for stopped state as well...
	if (regs.stopped)
	{
		m68k_set_irq2(intLevel);
		return;
	}

	// Since this can be called asynchronously, we need to fix it so that it
	// doesn't fuck up the main execution loop.
	IRQLevelToHandle = intLevel;
	checkForIRQToHandle = 1;
}


/* ASG: rewrote so that the int_level is a mask of the IPL0/IPL1/IPL2 bits */
void m68k_set_irq2(unsigned int intLevel)
{
	int oldLevel = regs.intLevel;
	regs.intLevel = intLevel;

	// A transition from < 7 to 7 always interrupts (NMI)
	// Note: Level 7 can also level trigger like a normal IRQ
	if (oldLevel != 0x07 && regs.intLevel == 0x07)
		m68ki_exception_interrupt(7);		// Edge triggered level 7 (NMI)
	else
		m68ki_check_interrupts();			// Level triggered (IRQ)
}


// Check for interrupts
static INLINE void m68ki_check_interrupts(void)
{
	if (regs.intLevel > regs.intmask)
		m68ki_exception_interrupt(regs.intLevel);
}


// Service an interrupt request and start exception processing
void m68ki_exception_interrupt(uint32_t intLevel)
{
	uint32_t vector, sr, newPC;

	m68kInterruptsServiced++;

	// Turn off the stopped state (N.B.: normal 68K behavior!)
	regs.stopped = 0;

	//JLH: need to add halt state?
	// prolly, for debugging/alpine mode... :-/
	// but then again, this should be handled already by the main execution loop :-P
	// If we are halted, don't do anything
	//	if (regs.stopped)
	//		return;

	// Acknowledge the interrupt (NOTE: This is a user supplied function!)
	vector = irq_ack_handler(intLevel);

	// Get the interrupt vector
	if (vector == M68K_INT_ACK_AUTOVECTOR)
		// Use the autovectors.  This is the most commonly used implementation
		vector = EXCEPTION_INTERRUPT_AUTOVECTOR + intLevel;
	else if (vector == M68K_INT_ACK_SPURIOUS)
		// Called if no devices respond to the interrupt acknowledge
		vector = EXCEPTION_SPURIOUS_INTERRUPT;
	else if (vector > 255)
	{
		//		M68K_DO_LOG_EMU((M68K_LOG_FILEHANDLE "%s at %08x: Interrupt acknowledge returned invalid vector $%x\n",
		//			 m68ki_cpu_names[CPU_TYPE], ADDRESS_68K(REG_PC), vector));
		return;
	}

	// The 68K has now committed to servicing this interrupt level.
	VJT_EMIT(VJT_EV_IRQ_DISPATCH, M68K, intLevel, 0);

	// Start exception processing
	sr = m68ki_init_exception();

	// Set the interrupt mask to the level of the one being serviced
	regs.intmask = intLevel;

	// Get the new PC
	newPC = m68k_read_memory_32(vector << 2);

	// If vector is uninitialized, call the uninitialized interrupt vector
	if (newPC == 0)
		newPC = m68k_read_memory_32(EXCEPTION_UNINITIALIZED_INTERRUPT << 2);

	// Generate a stack frame
	m68ki_stack_frame_3word(regs.pc, sr);

	m68k_setpc(newPC);
	M68KPrefetchFlush();	/* exception processing refills the queue */

	// Defer cycle counting until later
	regs.interruptCycles += 56;	// NOT ACCURATE-- !!! FIX !!!
	//	CPU_INT_CYCLES += CYC_EXCEPTION[vector];
}


// Initiate exception processing
static INLINE uint32_t m68ki_init_exception(void)
{
   uint32_t sr;

	MakeSR();
	sr = regs.sr;					// Save old status register

	/* Switch to the interrupt/supervisor stack BEFORE the frame is
	   pushed.  The 68000 keeps two stack pointers selected by the S bit,
	   and its documented exception processing sequence is

	       temp <- SR ; S <- 1 ; T <- 0 ; fetch vector ;
	       SSP <- SSP-4 ; M(SSP) <- PC ;
	       SSP <- SSP-2 ; M(SSP) <- temp ; PC <- handler

	   i.e. the frame lands on the SUPERVISOR stack, because setting S
	   is what makes A7 the SSP (M68000 Programmer's Reference Manual,
	   "Exception Processing Sequence").  Setting
	   regs.s without swapping A7 stacked interrupt frames on the USER
	   stack and left regs.usp stale, so the handler's RTE restored a
	   bogus user SP and clobbered regs.isp with the user value -- which
	   then became A7 on the next entry to supervisor mode.

	   This mirrors the two other privilege transitions in this core,
	   cpuextra.c::Exception() and cpuextra.c::MakeFromSR(); regs.isp is
	   guaranteed valid here because s can only have become 0 via
	   MakeFromSR(), which saves A7 into regs.isp on the way out.

	   Ported from BizHawk 1adb2b45 (waterbox Virtual Jaguar). */
	if (!regs.s)
	{
		regs.usp = m68k_areg(regs, 7);
		m68k_areg(regs, 7) = regs.isp;
		regs.s = 1;								// Set supervisor mode
	}

	return sr;
}


// 3 word stack frame (68000 only)
static INLINE void m68ki_stack_frame_3word(uint32_t pc, uint32_t sr)
{
	// Push PC on stack:
	m68k_areg(regs, 7) -= 4;
	m68k_write_memory_32(m68k_areg(regs, 7), pc);
	// Push SR on stack:
	m68k_areg(regs, 7) -= 2;
	m68k_write_memory_16(m68k_areg(regs, 7), sr);
}


unsigned int m68k_get_reg(void * context, m68k_register_t reg)
{
	if (reg <= M68K_REG_A7)
		return regs.regs[reg];
	else if (reg == M68K_REG_PC)
		return regs.pc;
	else if (reg == M68K_REG_SR)
	{
		MakeSR();
		return regs.sr;
	}
	else if (reg == M68K_REG_SP)
		return regs.regs[15];

	return 0;
}


void m68k_set_reg(m68k_register_t reg, unsigned int value)
{
	if (reg <= M68K_REG_A7)
		regs.regs[reg] = value;
	else if (reg == M68K_REG_PC)
	{
		regs.pc = value;
		M68KPrefetchFlush();	/* the queue is refilled from the new PC */
	}
	else if (reg == M68K_REG_SR)
	{
		regs.sr = value;
		MakeFromSR();
	}
	else if (reg == M68K_REG_SP)
		regs.regs[15] = value;
}


//
// Check if the instruction is a valid one
//
unsigned int m68k_is_valid_instruction(unsigned int instruction, unsigned int cpu_type)
{
	instruction &= 0xFFFF;

	if (cpuFunctionTable[instruction] == IllegalOpcode)
		return 0;

	return 1;
}


// Dummy functions, for now, until we prove the concept here. :-)

/* 68000 cycles executed so far inside the current m68k_execute() call.  Used
 * by GPUSyncToM68K() to work out how far the GPU has to be advanced when the
 * 68000 writes into GPU local RAM mid-slice (see gpu.c).  Valid only while
 * m68k_execute() is on the stack; callers outside it clamp the result.
 *
 * NOT monotonic, and not always spent-cycles: m68k_end_timeslice() moves
 * regs.remainingCycles into initialCycles and zeroes the former, so every
 * call after an early timeslice end reports the UNSPENT count instead.
 * GPUSyncToM68K() survives that because it clamps upward to the slice budget
 * and returns early when the delta is <= 0 -- a caller that needs a true
 * spent-cycle count must not use this without its own bound. */
int m68k_cycles_run(void) { return initialCycles - regs.remainingCycles; }
int m68k_cycles_remaining(void) { return 0; }        /* Number of cycles left */

void m68k_modify_timeslice(int cycles)
{
	regs.remainingCycles = cycles;
}


void m68k_end_timeslice(void)
{
	initialCycles = regs.remainingCycles;
	regs.remainingCycles = 0;
}


/* Read a 32-bit operand from any addressable EA the wrapper code uses.
 * The Removers/aln-built Jaguar binaries we care about always reach MULL/DIVL
 * with the EA = data-register-direct (mode 0). Other modes (immediate,
 * abs.W/L, (An), etc.) are emulated for completeness. */
static int read_long_ea(uint32_t opcode, uint32_t *out)
{
	uint32_t mode = (opcode >> 3) & 0x7;
	uint32_t reg  = opcode & 0x7;
	uint32_t ea;

	switch (mode)
	{
	case 0: /* Dn */
		*out = m68k_dreg(regs, reg);
		return 0;
	case 1: /* An */
		*out = m68k_areg(regs, reg);
		return 0;
	case 2: /* (An) */
		*out = m68k_read_memory_32(m68k_areg(regs, reg));
		return 0;
	case 5: /* (d16,An) */
	{
		int16_t d = (int16_t)get_iword(4);
		*out = m68k_read_memory_32(m68k_areg(regs, reg) + d);
		return 2;
	}
	case 7:
		switch (reg)
		{
		case 0: /* (xxx).W */
			ea = (int32_t)(int16_t)get_iword(4);
			*out = m68k_read_memory_32(ea);
			return 2;
		case 1: /* (xxx).L */
			ea = (uint32_t)get_ilong(4);
			*out = m68k_read_memory_32(ea);
			return 4;
		case 4: /* #imm */
			*out = (uint32_t)get_ilong(4);
			return 4;
		}
		break;
	}
	return -1;
}

/* Emulate the 68020+ MULL / DIVL instructions on a 68000-only core.
 * The Removers Library + m68k-atari-mint-gcc toolchain emits these for
 * 32x32 multiply and divide; without them, our binaries hard-hang inside
 * libgcc helpers. Returns 1 if handled, 0 to fall through to a true illegal
 * exception. */
static int handle_68020_mull_divl(uint32_t opcode)
{
	uint32_t base = opcode & 0xFFC0;
	uint16_t ext;
	uint32_t src;
	int extra;

	if (base != 0x4C00 && base != 0x4C40)
		return 0;

	ext = (uint16_t)get_iword(2);
	if (ext & 0x83F8)
		return 0;	/* reserved bits set — not a clean MULL/DIVL */

	extra = read_long_ea(opcode, &src);
	if (extra < 0)
		return 0;

	{
		uint32_t Dl = (ext >> 12) & 0x7;
		uint32_t Dh = ext & 0x7;
		int      sz = (ext >> 10) & 0x1;	/* 0=32-bit, 1=64-bit */
		int      sg = (ext >> 11) & 0x1;	/* 0=unsigned, 1=signed */

		if (base == 0x4C00)	/* MULL */
		{
			uint32_t a = m68k_dreg(regs, Dl);
			uint32_t b = src;
			if (sz == 0)
			{
				uint32_t r;
				if (sg)
				{
					int64_t sr = (int64_t)(int32_t)a * (int64_t)(int32_t)b;
					r = (uint32_t)sr;
					SET_VFLG(sr != (int64_t)(int32_t)r);
				}
				else
				{
					uint64_t ur = (uint64_t)a * (uint64_t)b;
					r = (uint32_t)ur;
					SET_VFLG((ur >> 32) != 0);
				}
				m68k_dreg(regs, Dl) = r;
				SET_NFLG(r >> 31);
				SET_ZFLG(r == 0);
				SET_CFLG(0);
			}
			else
			{
				uint64_t prod;
				if (sg)
					prod = (uint64_t)((int64_t)(int32_t)a * (int64_t)(int32_t)b);
				else
					prod = (uint64_t)a * (uint64_t)b;
				m68k_dreg(regs, Dl) = (uint32_t)prod;
				m68k_dreg(regs, Dh) = (uint32_t)(prod >> 32);
				SET_NFLG((prod >> 63) & 1);
				SET_ZFLG(prod == 0);
				SET_VFLG(0); SET_CFLG(0);
			}
		}
		else			/* DIVL */
		{
			uint32_t divisor = src;
			if (divisor == 0)
			{
				m68k_incpc(4 + extra);
				Exception(0x05, 0, M68000_EXC_SRC_CPU);
				return 1;
			}
			if (sz == 0)
			{
				uint32_t a = m68k_dreg(regs, Dl);
				if (sg)
				{
					int32_t  q = (int32_t)a / (int32_t)divisor;
					int32_t  r = (int32_t)a % (int32_t)divisor;
					m68k_dreg(regs, Dl) = (uint32_t)q;
					if (Dh != Dl) m68k_dreg(regs, Dh) = (uint32_t)r;
					SET_NFLG(q < 0); SET_ZFLG(q == 0);
				}
				else
				{
					uint32_t q = a / divisor;
					uint32_t r = a % divisor;
					m68k_dreg(regs, Dl) = q;
					if (Dh != Dl) m68k_dreg(regs, Dh) = r;
					SET_NFLG(q >> 31); SET_ZFLG(q == 0);
				}
			}
			else	/* 64-bit dividend in Dh:Dl */
			{
				uint64_t dividend = ((uint64_t)m68k_dreg(regs, Dh) << 32)
				                  | (uint64_t)m68k_dreg(regs, Dl);
				if (sg)
				{
					int64_t q = (int64_t)dividend / (int32_t)divisor;
					int64_t r = (int64_t)dividend % (int32_t)divisor;
					int32_t q32 = (int32_t)(uint32_t)q;
					m68k_dreg(regs, Dl) = (uint32_t)q;
					m68k_dreg(regs, Dh) = (uint32_t)r;
					SET_NFLG(q32 < 0); SET_ZFLG(q32 == 0);
				}
				else
				{
					uint64_t q = dividend / divisor;
					uint64_t r = dividend % divisor;
					uint32_t q32 = (uint32_t)q;
					m68k_dreg(regs, Dl) = q32;
					m68k_dreg(regs, Dh) = (uint32_t)r;
					SET_NFLG((q32 >> 31) & 1); SET_ZFLG(q32 == 0);
				}
			}
			SET_VFLG(0); SET_CFLG(0);
		}
	}

	m68k_incpc(4 + extra);
	return 1;
}

unsigned long IllegalOpcode(uint32_t opcode)
{
	if ((opcode & 0xFF80) == 0x4C00)
	{
		if (handle_68020_mull_divl(opcode))
			return 40;
	}

	if ((opcode & 0xF000) == 0xF000)
	{
		Exception(0x0B, 0, M68000_EXC_SRC_CPU);	// LineF exception...
		return 4;
	}
	else if ((opcode & 0xF000) == 0xA000)
	{
		Exception(0x0A, 0, M68000_EXC_SRC_CPU);	// LineA exception...
		return 4;
	}

	Exception(0x04, 0, M68000_EXC_SRC_CPU);		// Illegal opcode exception...
	return 4;
}


void BuildCPUFunctionTable(void)
{
	int i;
	unsigned long opcode;

	// We're only using the "fast" 68000 emulation here, not the "compatible"
	// ("fast" doesn't throw exceptions, so we're using "compatible" now :-P)
	//let's try "compatible" and see what happens here...
	const struct cputbl * tbl = op_smalltbl_5_ff;

	// Set all instructions to Illegal...
	for(opcode=0; opcode<65536; opcode++)
		cpuFunctionTable[opcode] = IllegalOpcode;

	// Move functions from compact table into our full function table...
	for(i=0; tbl[i].handler!=NULL; i++)
		cpuFunctionTable[tbl[i].opcode] = tbl[i].handler;

	//JLH: According to readcpu.c, handler is set to -1 and never changes.
	// Actually, it does read this crap in readcpu.c, do_merges() does it... :-P
	// Again, seems like a build time thing could be done here...
	for(opcode=0; opcode<65536; opcode++)
	{
		if (table68k[opcode].mnemo == i_ILLG || table68k[opcode].clev > 0)
			continue;

		if (table68k[opcode].handler != -1)
		{
			cpuop_func * f = cpuFunctionTable[table68k[opcode].handler];

			if (f == IllegalOpcode)
				abort();

			cpuFunctionTable[opcode] = f;
		}
	}
}


/* Save state serialization for 68K CPU */

size_t M68KStateSave(uint8_t *buf)
{
	uint8_t *start = buf;
	uint32_t pc_p_offset, pc_oldp_offset;

	/* Save register struct fields individually (not the raw struct,
	 * because pc_p/pc_oldp are pointers that differ per session). */
	STATE_SAVE_BUF(buf, regs.regs, sizeof(regs.regs));
	STATE_SAVE_VAR(buf, regs.usp);
	STATE_SAVE_VAR(buf, regs.isp);
	STATE_SAVE_VAR(buf, regs.sr);
	STATE_SAVE_VAR(buf, regs.s);
	STATE_SAVE_VAR(buf, regs.stopped);
	STATE_SAVE_VAR(buf, regs.intmask);
	STATE_SAVE_VAR(buf, regs.intLevel);
	STATE_SAVE_VAR(buf, regs.c);
	STATE_SAVE_VAR(buf, regs.z);
	STATE_SAVE_VAR(buf, regs.n);
	STATE_SAVE_VAR(buf, regs.v);
	STATE_SAVE_VAR(buf, regs.x);
	STATE_SAVE_VAR(buf, regs.pc);
	STATE_SAVE_VAR(buf, regs.spcflags);
	pf_pack();
	STATE_SAVE_VAR(buf, regs.prefetch_pc);
	STATE_SAVE_VAR(buf, regs.prefetch);
	STATE_SAVE_VAR(buf, regs.remainingCycles);
	STATE_SAVE_VAR(buf, regs.interruptCycles);

	/* Save pc_p and pc_oldp as offsets from jagMemSpace */
	pc_p_offset = (uint32_t)(regs.pc_p ? (regs.pc_p - jagMemSpace) : 0xFFFFFFFF);
	pc_oldp_offset = (uint32_t)(regs.pc_oldp ? (regs.pc_oldp - jagMemSpace) : 0xFFFFFFFF);
	STATE_SAVE_VAR(buf, pc_p_offset);
	STATE_SAVE_VAR(buf, pc_oldp_offset);

	/* Local statics */
	STATE_SAVE_VAR(buf, initialCycles);
	STATE_SAVE_VAR(buf, checkForIRQToHandle);
	STATE_SAVE_VAR(buf, IRQLevelToHandle);

	return (size_t)(buf - start);
}


size_t M68KStateLoad(const uint8_t *buf)
{
	const uint8_t *start = buf;
	uint32_t pc_p_offset, pc_oldp_offset;

	STATE_LOAD_BUF(buf, regs.regs, sizeof(regs.regs));
	STATE_LOAD_VAR(buf, regs.usp);
	STATE_LOAD_VAR(buf, regs.isp);
	STATE_LOAD_VAR(buf, regs.sr);
	STATE_LOAD_VAR(buf, regs.s);
	STATE_LOAD_VAR(buf, regs.stopped);
	STATE_LOAD_VAR(buf, regs.intmask);
	STATE_LOAD_VAR(buf, regs.intLevel);
	STATE_LOAD_VAR(buf, regs.c);
	STATE_LOAD_VAR(buf, regs.z);
	STATE_LOAD_VAR(buf, regs.n);
	STATE_LOAD_VAR(buf, regs.v);
	STATE_LOAD_VAR(buf, regs.x);
	STATE_LOAD_VAR(buf, regs.pc);
	STATE_LOAD_VAR(buf, regs.spcflags);
	STATE_LOAD_VAR(buf, regs.prefetch_pc);
	STATE_LOAD_VAR(buf, regs.prefetch);
	pf_unpack();
	STATE_LOAD_VAR(buf, regs.remainingCycles);
	STATE_LOAD_VAR(buf, regs.interruptCycles);

	/* Reconstruct pc_p and pc_oldp from offsets */
	STATE_LOAD_VAR(buf, pc_p_offset);
	STATE_LOAD_VAR(buf, pc_oldp_offset);
	regs.pc_p = (pc_p_offset != 0xFFFFFFFF) ? (jagMemSpace + pc_p_offset) : NULL;
	regs.pc_oldp = (pc_oldp_offset != 0xFFFFFFFF) ? (jagMemSpace + pc_oldp_offset) : NULL;

	STATE_LOAD_VAR(buf, initialCycles);
	STATE_LOAD_VAR(buf, checkForIRQToHandle);
	STATE_LOAD_VAR(buf, IRQLevelToHandle);

	return (size_t)(buf - start);
}
