/*
 * Committed fallback for src/core/version.h.
 *
 * version.h is generated by scripts/gen-version-h.sh and gitignored: it
 * carries the short git rev, so it cannot be committed without every build
 * dirtying the tree.  The Makefile and jni/Android.mk both run the
 * generator at parse time, so for them version.h always exists and always
 * wins -- libretro.c prefers it via __has_include and never reads this
 * file.
 *
 * Build systems with no hook to run a shell script before compiling have
 * no version.h at all, and used to fail on the #include outright.  The
 * SwiftPM manifest used by the Provenance frontend is the case this exists
 * for.  Those builds get the values below.
 *
 * CORE_BASE_VERSION is a deliberate copy of the value in the Makefile,
 * which stays the single source of truth.  Nothing rewrites this file
 * automatically, on purpose: the generator runs at Makefile *parse* time,
 * on every build including `make lint`, so a generator that edited a
 * tracked file would dirty the working tree on every build -- feeding a
 * false "-dirty" into scripts/build-id.sh and the VJ_EXPECT_BUILD guard,
 * and recreating exactly the silent-overwrite footgun this file replaces.
 * The copy is kept honest by CI instead (the "version fallback in sync"
 * step in .github/workflows/c-cpp.yml), which fails loudly on divergence
 * rather than quietly fixing it -- the same shape as the
 * docs/cd-boot-matrix.md drift guard.
 *
 * If you bump CORE_BASE_VERSION in the Makefile, bump it here too.
 */

#ifndef VJAG_VERSION_H
#define VJAG_VERSION_H

/* Keep in sync with CORE_BASE_VERSION in the Makefile. */
#define CORE_BASE_VERSION "v3.5.1"

/* Spelled so it cannot be mistaken for a real rev in a bug report: a build
 * that reports this had no git metadata available at compile time. */
#ifndef GIT_VERSION
#define GIT_VERSION " unknown-rev"
#endif

#ifdef BUILD_TIMESTAMP
#define CORE_VERSION CORE_BASE_VERSION GIT_VERSION " " BUILD_TIMESTAMP
#else
#define CORE_VERSION CORE_BASE_VERSION GIT_VERSION
#endif

#endif /* VJAG_VERSION_H */
