#!/usr/bin/env bash
# Generates src/core/version.h from CORE_BASE_VERSION pinned in
# Makefile + the current short git rev.  Called by the Makefile on
# every build (FORCE rule) and by the c-cpp.yml msvc-check step which
# invokes cl.exe directly without going through make.
#
# Output is gitignored.  Re-runs are content-aware: if the new
# contents match the existing file, the mtime is left alone so
# incremental builds don't needlessly rebuild libretro.o.

set -e

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/src/core/version.h"

# Portable sed extraction that works on both GNU and BSD sed.
CORE_BASE_VERSION=$(sed -n 's/^CORE_BASE_VERSION[[:space:]]*:*=[[:space:]]*\(.*\)/\1/p' "$ROOT/Makefile" | head -1)
if [ -z "$CORE_BASE_VERSION" ]; then
  echo "gen-version-h.sh: failed to read CORE_BASE_VERSION from Makefile" >&2
  exit 1
fi

GIT_REV=$(cd "$ROOT" && git rev-parse --short HEAD 2>/dev/null || echo unknown)

mkdir -p "$(dirname "$OUT")"
TMP="$OUT.tmp"
cat > "$TMP" << EOF
/* Auto-generated by scripts/gen-version-h.sh.  Do not edit; do not commit. */
#ifndef VJAG_VERSION_H
#define VJAG_VERSION_H
#define CORE_BASE_VERSION "${CORE_BASE_VERSION}"
#define GIT_VERSION " ${GIT_REV}"
#ifdef BUILD_TIMESTAMP
#define CORE_VERSION CORE_BASE_VERSION GIT_VERSION " " BUILD_TIMESTAMP
#else
#define CORE_VERSION CORE_BASE_VERSION GIT_VERSION
#endif
#endif
EOF

if cmp -s "$TMP" "$OUT" 2>/dev/null; then
  rm "$TMP"
else
  mv "$TMP" "$OUT"
fi
